// build-config.js
// -----------------------------------------------------------------------------
// Generates config.js from environment variables at DEPLOY time.
//
// Why: config.js holds secret API keys and is gitignored, so it never reaches
// the git-connected Cloudflare Pages build. This script writes config.js on the
// build server from Pages "Environment variables", so secrets stay out of the
// repo but still ship to the live site.
//
// Cloudflare Pages → Settings → Build:
//   Build command:           node scripts/build-config.js
//   Build output directory:  /            (this is a static site, served from root)
//
// Cloudflare Pages → Settings → Environment variables (set the secrets):
//   OPENWEATHERMAP_API_KEY   (required for live weather)
//   GOOGLE_CALENDAR_ID       (public calendar id — for the Calendar tab/agenda)
//   GOOGLE_API_KEY           (Google Calendar API key)
//   LAT, LON, ZIP, LOCATION_LABEL  (optional — defaults below are Franklin, TN)
//
// Pure Node, no dependencies. Locally you don't need this — keep your hand-
// maintained config.js. It's only here so the live site gets real keys.
// -----------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

const env = process.env;

// Non-secret location defaults (Franklin, TN). Overridable via env.
const cfg = {
  OPENWEATHERMAP_API_KEY: env.OPENWEATHERMAP_API_KEY || '',
  GOOGLE_CALENDAR_ID: env.GOOGLE_CALENDAR_ID || '',
  GOOGLE_API_KEY: env.GOOGLE_API_KEY || '',
  LAT: env.LAT != null && env.LAT !== '' ? Number(env.LAT) : 35.9251,
  LON: env.LON != null && env.LON !== '' ? Number(env.LON) : -86.8689,
  ZIP: env.ZIP || '37064',
  LOCATION_LABEL: env.LOCATION_LABEL || 'Franklin, TN',
};

if (!cfg.OPENWEATHERMAP_API_KEY) {
  console.warn(
    '[build-config] WARNING: OPENWEATHERMAP_API_KEY is not set — the deployed ' +
    'site will fall back to placeholder weather. Set it in Cloudflare Pages ' +
    'environment variables.'
  );
}

const out =
  '// config.js — GENERATED by scripts/build-config.js at deploy time.\n' +
  '// Do not edit; values come from Cloudflare Pages environment variables.\n' +
  'const CONFIG = ' + JSON.stringify(cfg, null, 2) + ';\n';

const target = path.join(__dirname, '..', 'config.js');
fs.writeFileSync(target, out);
console.log(`[build-config] wrote ${target} (weather key: ${cfg.OPENWEATHERMAP_API_KEY ? 'set' : 'MISSING'})`);
